'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace AgentWebServices
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AgentWebServices.AgentManagementWebServicesSoap")>  _
    Public Interface AgentManagementWebServicesSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ValidateAgentAndDevice", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidateAgentAndDevice(ByVal strAgentID As String, ByVal strDeviceID As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ValidateLogin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ValidateLogin(ByVal strAgentID As String, ByVal strPassword As String, ByVal strDeviceID As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SaveDocument", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SaveDocument(ByVal strBinary As String, ByVal strDocName As String, ByVal strFolder As String, ByVal strSource As String, ByVal agentID As String, ByVal totalFile As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RetrievePolicyNumber", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RetrievePolicyNumber(ByVal agentCode As String, ByVal strPolNo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EncryptAll", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EncryptAll(ByVal strBinary As String, ByVal strDocName As String, ByVal strFolder As String, ByVal strSource As String, ByVal agentID As String, ByVal totalFile As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AgentManagementWebServicesSoapChannel
        Inherits AgentWebServices.AgentManagementWebServicesSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AgentManagementWebServicesSoapClient
        Inherits System.ServiceModel.ClientBase(Of AgentWebServices.AgentManagementWebServicesSoap)
        Implements AgentWebServices.AgentManagementWebServicesSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ValidateAgentAndDevice(ByVal strAgentID As String, ByVal strDeviceID As String) As String Implements AgentWebServices.AgentManagementWebServicesSoap.ValidateAgentAndDevice
            Return MyBase.Channel.ValidateAgentAndDevice(strAgentID, strDeviceID)
        End Function
        
        Public Function ValidateLogin(ByVal strAgentID As String, ByVal strPassword As String, ByVal strDeviceID As String) As String Implements AgentWebServices.AgentManagementWebServicesSoap.ValidateLogin
            Return MyBase.Channel.ValidateLogin(strAgentID, strPassword, strDeviceID)
        End Function
        
        Public Function SaveDocument(ByVal strBinary As String, ByVal strDocName As String, ByVal strFolder As String, ByVal strSource As String, ByVal agentID As String, ByVal totalFile As String) As String Implements AgentWebServices.AgentManagementWebServicesSoap.SaveDocument
            Return MyBase.Channel.SaveDocument(strBinary, strDocName, strFolder, strSource, agentID, totalFile)
        End Function
        
        Public Function RetrievePolicyNumber(ByVal agentCode As String, ByVal strPolNo As String) As String Implements AgentWebServices.AgentManagementWebServicesSoap.RetrievePolicyNumber
            Return MyBase.Channel.RetrievePolicyNumber(agentCode, strPolNo)
        End Function
        
        Public Function EncryptAll(ByVal strBinary As String, ByVal strDocName As String, ByVal strFolder As String, ByVal strSource As String, ByVal agentID As String, ByVal totalFile As String) As String Implements AgentWebServices.AgentManagementWebServicesSoap.EncryptAll
            Return MyBase.Channel.EncryptAll(strBinary, strDocName, strFolder, strSource, agentID, totalFile)
        End Function
    End Class
End Namespace
